export const users = [
  {
    "id": 1,
    "username": "ProGamer698",
    "name": "Alex Brown",
    "email": "alex.brown@example.com",
    "location": "Mumbai, India",
    "status": "active",
    "verified": false,
    "deposits": 7821.98,
    "withdrawals": 34.78,
    "balance": 7787.2,
    "lastActive": "8 hour(s) ago",
    "joined": "2023-08-23",
    "avatar": "https://i.pravatar.cc/150?img=52"
  },
  {
    "id": 2,
    "username": "Cool510",
    "name": "Natalie Green",
    "email": "natalie.green@example.com",
    "location": "Los Angeles, USA",
    "status": "active",
    "verified": true,
    "deposits": 8338.56,
    "withdrawals": 4480.87,
    "balance": 3857.69,
    "lastActive": "4 hour(s) ago",
    "joined": "2023-07-21",
    "avatar": "https://i.pravatar.cc/150?img=4"
  },
  {
    "id": 3,
    "username": "Elite529",
    "name": "Tom Clark",
    "email": "tom.clark@example.com",
    "location": "Edinburgh, UK",
    "status": "suspended",
    "verified": false,
    "deposits": 929.39,
    "withdrawals": 226.7,
    "balance": 702.69,
    "lastActive": "6 hour(s) ago",
    "joined": "2023-05-11",
    "avatar": "https://i.pravatar.cc/150?img=32"
  },
  {
    "id": 4,
    "username": "ProGamer974",
    "name": "Sarah Hacker",
    "email": "sarah.hacker@example.com",
    "location": "London, UK",
    "status": "active",
    "verified": true,
    "deposits": 3488.33,
    "withdrawals": 1030.65,
    "balance": 2457.68,
    "lastActive": "4 hour(s) ago",
    "joined": "2023-12-14",
    "avatar": "https://i.pravatar.cc/150?img=50"
  },
  {
    "id": 5,
    "username": "Cool868",
    "name": "Tom Green",
    "email": "tom.green@example.com",
    "location": "Edinburgh, UK",
    "status": "suspended",
    "verified": false,
    "deposits": 7277.43,
    "withdrawals": 3335.47,
    "balance": 3941.96,
    "lastActive": "5 hour(s) ago",
    "joined": "2023-11-08",
    "avatar": "https://i.pravatar.cc/150?img=6"
  },
  {
    "id": 6,
    "username": "Bullet276",
    "name": "Priya Scott",
    "email": "priya.scott@example.com",
    "location": "Edinburgh, UK",
    "status": "suspended",
    "verified": true,
    "deposits": 5639.66,
    "withdrawals": 1297.64,
    "balance": 4342.02,
    "lastActive": "6 hour(s) ago",
    "joined": "2023-02-26",
    "avatar": "https://i.pravatar.cc/150?img=23"
  },
  {
    "id": 7,
    "username": "Hunter193",
    "name": "Rahul Wilson",
    "email": "rahul.wilson@example.com",
    "location": "Edinburgh, UK",
    "status": "suspended",
    "verified": false,
    "deposits": 2965.87,
    "withdrawals": 988.14,
    "balance": 1977.73,
    "lastActive": "7 hour(s) ago",
    "joined": "2023-07-26",
    "avatar": "https://i.pravatar.cc/150?img=6"
  },
  {
    "id": 8,
    "username": "Sniper401",
    "name": "Ben Ramesh",
    "email": "ben.ramesh@example.com",
    "location": "Delhi, India",
    "status": "suspended",
    "verified": true,
    "deposits": 9417.12,
    "withdrawals": 4078.58,
    "balance": 5338.54,
    "lastActive": "8 hour(s) ago",
    "joined": "2023-12-15",
    "avatar": "https://i.pravatar.cc/150?img=25"
  },
  {
    "id": 9,
    "username": "Sharp408",
    "name": "David Green",
    "email": "david.green@example.com",
    "location": "Berlin, Germany",
    "status": "active",
    "verified": true,
    "deposits": 4052.72,
    "withdrawals": 2906.74,
    "balance": 1145.98,
    "lastActive": "12 hour(s) ago",
    "joined": "2023-11-18",
    "avatar": "https://i.pravatar.cc/150?img=47"
  },
  {
    "id": 10,
    "username": "Sniper997",
    "name": "Natalie Brown",
    "email": "natalie.brown@example.com",
    "location": "London, UK",
    "status": "active",
    "verified": false,
    "deposits": 9967.92,
    "withdrawals": 7732.76,
    "balance": 2235.16,
    "lastActive": "10 hour(s) ago",
    "joined": "2023-10-02",
    "avatar": "https://i.pravatar.cc/150?img=23"
  },
  {
    "id": 11,
    "username": "Bullet944",
    "name": "Emma Clark",
    "email": "emma.clark@example.com",
    "location": "Delhi, India",
    "status": "active",
    "verified": false,
    "deposits": 5509.93,
    "withdrawals": 4122.17,
    "balance": 1387.76,
    "lastActive": "3 hour(s) ago",
    "joined": "2023-08-11",
    "avatar": "https://i.pravatar.cc/150?img=12"
  },
  {
    "id": 12,
    "username": "Speed506",
    "name": "Liam Hacker",
    "email": "liam.hacker@example.com",
    "location": "London, UK",
    "status": "active",
    "verified": false,
    "deposits": 2570.24,
    "withdrawals": 1206.35,
    "balance": 1363.89,
    "lastActive": "3 hour(s) ago",
    "joined": "2023-10-28",
    "avatar": "https://i.pravatar.cc/150?img=22"
  },
  {
    "id": 13,
    "username": "Ghost890",
    "name": "Tom Doe",
    "email": "tom.doe@example.com",
    "location": "New York, USA",
    "status": "active",
    "verified": false,
    "deposits": 2805.31,
    "withdrawals": 1221.07,
    "balance": 1584.24,
    "lastActive": "2 hour(s) ago",
    "joined": "2023-02-21",
    "avatar": "https://i.pravatar.cc/150?img=34"
  },
  {
    "id": 14,
    "username": "Sharp237",
    "name": "John Chen",
    "email": "john.chen@example.com",
    "location": "London, UK",
    "status": "suspended",
    "verified": false,
    "deposits": 5364.22,
    "withdrawals": 935.68,
    "balance": 4428.54,
    "lastActive": "12 hour(s) ago",
    "joined": "2023-06-22",
    "avatar": "https://i.pravatar.cc/150?img=42"
  },];
